### ISSUE TITLE
Reproduce point pattern to a larger window-extent

### ISSUE THREAD

**Issue by kiranaw** [r-spatialecology/shar#67]
Hello, 

I would like to reconstruct a point pattern from a small tree plot data to a larger size (eg. from 0.3 ha to 1 ha). 
For this, I tried reconstruct_pattern_marks(). However, I learned that it will produce a pattern with the same number of points.
Do you have any advice, which function I can use for this? I wonder if there is an option to vary the number of points and window-extent to reconstruct. 

Thanks, 
kiranaw

**Comment by mhesselbarth** [comment]
Hey Kiranaw, 

currently, that is not possible because as you already said, `shar` can only reconstruct patterns with the same number of points and extent.

However, I really like your idea and this shouldn't be too hard to implement. I might find some time next week to have a closer look at this.

**Comment by mhesselbarth** [comment]
caf331d2b0cfd6b4adde0ff24c9fb990878913fc

@kiranaw Please try to install `shar` using `remotes::install_github("r-spatialecology/shar", ref = "n_points")`. This installs the latest development version which allows you to specify the number of points and a window to reconstruct a homogenous pattern (`reconstruct_pattern_homo`) with different number of points or within a different window. This pattern can then be used to reconstruct the marks (`reconstruct_pattern_marks`) which now also works if the number of points are not identical between the pattern to reconstruct and the observed pattern. 

``` r
library(shar)

# reconstruct spatial structure only
pattern_recon <- reconstruct_pattern_homo(shar::species_a, n_points = 70, 
                                          window = spatstat.geom::owin(xrange = c(0, 900), 
                                                                       yrange = c(0, 1100)),
                                          n_random = 1, max_runs = 1000, verbose = FALSE)

# should be false
pattern_recon$observed$n == pattern_recon$randomized$randomized_1$n
#> [1] FALSE

# get only numeric marks of input pattern
marks_sub <- spatstat.geom::subset.ppp(shar::species_a, select = dbh)

# reconstruct marks
marks_recon <- shar::reconstruct_pattern_marks(pattern = pattern_recon$randomized$randomized_1,
                                               marked_pattern = marks_sub,
                                               n_random = 1,
                                               max_runs = 1000, verbose = FALSE)

# should be false again
marks_recon$randomized$randomized_1$n == shar::species_a$n
#> [1] FALSE

# this should be true
marks_recon$randomized$randomized_1$n == pattern_recon$randomized$randomized_1$n
#> [1] TRUE
```

<sup>Created on 2021-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This link might be also interesting in case you want to reconstruct several patterns: https://r-spatialecology.github.io/shar/articles/articles/reconstruct_multiple_patterns.html

**Comment by kiranaw** [comment]
Hi @mhesselbarth, thanks a lot for adding this feature! I tried it and it worked. Glad that now it is possible to give a number of points and window extent to reconstruct a point pattern. This is really helpful.

Cheers,
kiranaw

**Comment by mhesselbarth** [comment]
Perfect. Will also be part of the next CRAN update within the next couple of days then. 

I will close this for now, please re-open if needed.
