### ISSUE TITLE
Why a point pattern approach to habitat analyses

### ISSUE THREAD

**Issue by tretherington** [r-spatialecology/shar#80]
Regarding @openjournals/joss-reviews#3811 requirement for a statement of need, I am not aware of any point pattern software in R that allows someone to do habitat analyses, so in that regard I am happy that this software fills a gap.

However, I think it would be helpful for me to understand if there are situations where this approach is beneficial over the multitude of other ways I could take xy point data and a raster and produce some sort of habitat/species distribution/ecological niche model.

I don't feel like I can articulate this question very well, so I do apologise for that :grimacing:, and I haven't had time to fully read and digest the cited papers, but I think it could be very helpful to potential users to understand any specific instances where these kinds of approaches are beneficial when compared to other similar presence-background approaches available in R packages such as dismo, biomod2, zoon, adehabitat, and the like.

I guess I would say that at the moment I don't see what the benefit of treating my xy location data as a point pattern and analysing it though shar.

I am mentioning this as if you can highlight that benefit somehow, then I think you will increase the likelihood of ecologists engaging with shar.

**Comment by mhesselbarth** [comment]
5e7b241161f9a54c0c9cdac55b087e0f25a6ae46
 
I tried to add a few (short) explanation why the approach is interesting including:
- point pattern act as memory of processes that shaped them
- approach has very few assumptions of data characteristics because it automatically controls for spatial autocorrelation and dependence between points
- designed for discrete environmental data

I hope that answer your questions (at least to a degree...).

**Comment by tretherington** [comment]
Thanks for expanding on these points, and having now skimmed through the cited papers I think you have emphasised the importance of the spatial patterning within the points, and why using a purely random approach is not entirely useful.  I have not considered this before, so this has been a useful concept for me to learn, so I appreciate the effort you have gone to here.
