### ISSUE TITLE
Axis in pair correlation plots

### ISSUE THREAD

**Issue by lionel68** [r-spatialecology/shar#84]
This is related to openjournals/joss-reviews#3811, the pair correlation plots from `plot_reconstructed_pattern` sometime show axis that do not span the whole range of the data:

```
pp <- spatstat.core::rLGCP(win=spatstat.geom::owin(c(0, 10), c(0, 10)))
ff <- fit_point_process(pp)
plot_reconstructed_pattern(ff)
```
![pcof](https://user-images.githubusercontent.com/7189850/138111789-b0231fae-e058-4c1b-9340-d948a8c87d2e.png)

**Comment by mhesselbarth** [comment]
68a58204570ba046330760374ee9f2a508b696d4
Fixed. The y range is based on the min/max values now

``` r
library(shar)
library(spatstat)
pp <- spatstat.core::rLGCP(win=spatstat.geom::owin(c(0, 10), c(0, 10)))
ff <- fit_point_process(pp)
plot(ff, ask = FALSE)
```

![](https://i.imgur.com/VOqmJpZ.png)![](https://i.imgur.com/OsZwvN2.png)

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
