### ISSUE TITLE
Clarify expectations around NA data in the raster landscape

### ISSUE THREAD

**Issue by tretherington** [r-spatialecology/shar#87]
Regarding [https://github.com/openjournals/joss-reviews/issues/3811](https://github.com/openjournals/joss-reviews/issues/3811) I think there should be a note somewhere, perhaps in the README or the paper, maybe both around the expectation of how NA data in the raster landscape would be handled.

All the examples and supporting papers cited seem to work with landscapes that are "complete" in that points can occur anywhere within the unit-square for the point-process models and there is habitat everywhere within the raster landscape.  But I suspect that in reality it will be quite common for the study area to be a more complex shape than a rectangle, and therefore there will be NA cells within the raster landscape in which points cannot occur.  So I am left wondering if it is theoretically reasonable to use the methods in `shar` with that kind of data.  Essentially I am querying how NA data in a raster landscape is handled.

If `shar` can't handle NA data that is absolutely fine, but I do think it should be highlighted to potential users if that will preclude use of the package so that they can quickly eliminate `shar` as an option if it won't work for them.

Apologies if I have missed that information somewhere, but if it does exist, perhaps it could be made more prominent as I think that could have a massive bearing for potential users.

**Comment by mhesselbarth** [comment]
That is a very good point and I do agree this should be addressed. IMO, probably both in the readme as well as in the paper. 

All methods with, exception of the torus translation, should be able "to handle" NAs in a way that they can be present under the prerequisite that a raster NA cell means that also no point could show up there (e..g think of a lake and tree locations). What is not allowed, that there are missing environmental data for cells of the landscape in which points can be present.

**Comment by mhesselbarth** [comment]
fc5c6cf2d2590c5931d7289bfc7cc52db6c2650d , 1e8484691e6f81106927ec680bd8ba9a764c2647

Fixed. Please re-open if explanation is not sufficient enough.
