### ISSUE TITLE
Include breaks into results_habitat_association

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/shar#97]
@ZekeMarshall had the idea to not include the breaks additionally to the classes in the `results_habitat_association()` table. 

That's a good idea, however, the breaks are not necessarily included in the provided raster object. Maybe add an argument (default `NA` or `NULL`), which allows providing breaks in the same order as classes. In this case, the breaks from `classifiy_habitats` could be used. Or maybe a `data.frame` which would allow to merge classes to breaks.

Related, maybe write a short helper function to convert the `classInterval ` object as `data.frame`.

**Comment by ZekeMarshall** [comment]
Looks great @mhesselbarth ! I'll wait until this has successfully merged in to main, then update my vignette before sending my pull request!

**Comment by mhesselbarth** [comment]
Sounds good...Some of the CI tests are failing, I need to look into why

**Comment by mhesselbarth** [comment]
I don't thing the CI tests failures are due to some other packages being updated and not the `shar` code. Because I now get the same error even on the `CRAN` branch.

**Comment by mhesselbarth** [comment]
Merged

**Comment by ZekeMarshall** [comment]
Thanks @mhesselbarth , just tested this functionality, works perfectly!
